apiVersion: v1
kind: Service
metadata:
  name: catsnewyear-front
  labels:
    env: production
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: catsnewyear-front
